# Compose configuration file for Lab 2

version: '3'
services:
  database:
    image: postgres:14
    hostname: 'db.ticktock.lab'
    restart: always
    env_file:
      - 'config/ticktock/database.env'
    ports:
      - '5432:5432'
    volumes:
      - dbstore:/var/lib/postgresql/data

  # TickTock webserver
  webserver:
    image: '${DOCKER_REPO}/ticktock-web:latest'
    build: ./ticktock-web
    restart: unless-stopped
    entrypoint: ['sh', '/scripts/run.sh']
    hostname: 'www.ticktock.lab'
    ports:
      - '5000:5000'
    environment:
      DB_HOST: 'db.ticktock.lab'
      SECRET_KEY: 'ce330a3f5aeca29730768e9db4f6a045c772b4e5432d3608f65637a9d03b5681'
      GUNICORN_RELOAD: '${GUNICORN_RELOAD:-1}'
    env_file:
      - 'config/ticktock/database.env'
      - 'config/ticktock/admin_pass.env'
      - 'config/ticktock/buckets.env'
      - 'config/ticktock/recon_flags.env'
    depends_on:
      - database
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  dbstore:
