services:

  proxy:
    # Use the gallery proxy configuration
    environment:
      NGINX_ADDTL_CONFD: "gallery.conf,vuln.conf"

  rclone:
    image: '${DOCKER_REPO}/ticktock-gallery-rclone:latest'
    networks:
      - ticktocknet
    build: ./ticktock/ticktock-gallery-rclone
    env_file:
      - 'config/ticktock/admin_pass.env'
    depends_on:
      - minio
    volumes:
      - type: bind
        source: /tmp/ticktock-gallery
        target: /s3
        bind:
          propagation: rshared
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

    # Required to allow rclone FUSE mounts inside of the container.
    # Note that this is generally quite insecure.
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined

  # Apache httpd webserver running the TickTock gallery
  gallery:
    image: '${DOCKER_REPO}/ticktock-gallery:latest'
    hostname: 'gallery.ticktock.lab'
    networks:
      - ticktocknet
    build: ./ticktock/ticktock-gallery
    env_file:
      - 'config/ticktock/admin_pass.env'
    depends_on:
      - rclone
      - minio
    volumes:
      - type: bind
        source: /tmp/ticktock-gallery
        target: /s3
        bind:
          propagation: rslave
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  # Vulnerable httpd server
  httpd-vuln:
    image: '${DOCKER_REPO}/cve-2021-42013-httpd:latest'
    build: ./CVE-2021-42013-httpd
    hostname: 'vuln.ticktock.lab'
    networks:
      - ticktockdmz
    env_file:
      - 'config/ticktock/rce_testing.env'
    ports:
      - 10000:80

networks:
  ticktockdmz:
